RESTORE DATABASE [test2] FROM  DISK = N'E:\MSSQL\test.bak' WITH  FILE = 1,  
MOVE N'test' TO N'E:\MSSQL\DBE\MSSQL16.MSSQLSERVER\MSSQL\DATA\test2',  
MOVE N'test_log' TO N'E:\MSSQL\DBE\MSSQL16.MSSQLSERVER\MSSQL\DATA\test2_log'